version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: springboot-mysql
    ports:
      - "3306:3306"
      - "33060:33060"
    environment:
      MYSQL_ROOT_PASSWORD: "1111"
      MYSQL_DATABASE: "springbatch"
