version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb_container
    environment:
      MARIA_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: event
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    ports:
      - "3306:3306"
    volumes:
      - ./mariadb/conf.d:/etc/mysql/conf.d
      - ./mariadb/data:/var/lib/mysql
      - ./initdb.d:/docker-entrypoint-initdb.d

volumes:
  mariadb_data:
