spring:
  application:
    name: dynamodb-practice
  datasource:
    url: jdbc:mariadb://localhost:3306/event
    username: user
    password: userpassword
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
amazon:
  dynamodb:
    endpoint: http://localhost:8000/
  aws:
    accesskey: key
    secretkey: key2